title: "Alvaro Lacasa"
logo: "/img/1677447848171.jfif"
description: "Contact me on LinkedIn!
https://www.linkedin.com/in/alvaro-lacasa-vela-363557210"
show_downloads: true
theme: jekyll-theme-minimal
