title: Alvaro Lacasa
logo: /img/1677447848171.jfif
description: ## Contact
- **Email:** alvaro.lacasa.vela@gmail.com
- **Location:** Barcelona, Spain
- **[LinkedIn](https://www.linkedin.com/in/alvaro-lacasa-vela-363557210)**
- **[Bold Profile](https://bold.pro/my/alvaro-lacasavela)**
show_downloads: true

theme: jekyll-theme-minimal
